---
title: "Covariate Minimization Simualtion"
author: "BACPAC "
date: "5/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libs, echo =TRUE, include=FALSE}
library(tidyverse)
library(fabricatr)
library(furrr)
if (str_detect(here::here(), "jsperger") == TRUE) plan(multisession, workers = 12) else plan(sequential)

```


```{r minimization}
#' input: 
#' @param Z - matrix of integers. Columns are factors, rows are subjects, and integer represent a level for the corresponding factor/column. For a factor with k levels, the corresponding column should take integer values between 1 and k. We assume all levels of all factors appear at least once in the observed data.
#' @param N - number of treatment groups
#' @param DFunc: function to assess variation 
#' @param weights: vector of factor weights when some factors are more important than others
#' @param formula: choices are a,b,c, corresponding to randomization probability formulas in section 3.3 of paper
#' @param bias: the constant associated with the randomization probability formula in paper. larger values yield less stochasticity. For example, for formula='a', range from 1/N (every assignment equal) to 1 (assignment deterministic). See paper for details. 
#' @param print.flag If TRUE it will print the imbalance matrix every 100 time-steps starting at the first patient
#' 

balanceRandomize = function(Z, N, DFunc = function(x) diff(range(x)), weights=1, formula='a', bias = 1, print.flag = FALSE) {
  numSubj = nrow(Z) #number of subjects
  M = ncol(Z) #number of factors
  f = apply(Z, 2, max) #number of levels for each factor
  X = array(NA, dim = c(M,max(f),N)) #X[i,j,k] gives number of subjects with level j of factor i in group k
  for (i in 1:M) X[i,1:f[i],] = 0 #NA for j>f[i], 0 otherwise
  dk = vector("double", M) 
  G = vector("double", N) 
  assignment = vector("double", numSubj) 
  p = vector('double', N) #treatment assignment probabilities for subject s
  error = 0
  for (s in 1:numSubj) { #assign next subject s, given current count array X
    if(print.flag == TRUE & s %% 100 == 1){
      print(paste0("Current X at subject ", s))
      print(X)
    }
    
    r = Z[s,] #factor levels for subject s
    
     #calculate Gk for each k=1,...,N (see paper)
    for (k in 1:N) {
      
      #calculate dik for each i=1,...,M (see paper)
      for (i in 1:M) {
        Xk = X 
        Xk[i, r[i], k] = Xk[i, r[i], k] + 1 
        dk[i] = DFunc(Xk[i,r[i],])
      }
      
      G[k] = sum(weights*dk)
    }
    
#    set.seed(42)
    if (formula=='a') {
      bestAssign = which(G==min(G))
      prefer = ifelse(length(bestAssign)==1, bestAssign, sample(bestAssign, 1)) #if ties, break randomly
      p[prefer] = bias
      p[-c(prefer)] = (1-bias)/(N-1) 
    } else if (formula=='c') {
      p = (1/(N-bias))*(1-bias*G/sum(G))
    } else if (formula=='b') {
      p = bias-2*(N*bias-1)/(N*(N+1))*rank(G, ties.method = 'random')
    }
    if (sum(p)!=1) error=1
    assignment[s] = sample(x = 1:N, size = 1, prob = p) #treatment assignment for subject s
    for (i in 1:M) X[i,r[i],assignment[s]] = X[i,r[i],assignment[s]]+1 #update X
  }
  return(list(assignment = assignment, X = X, error = error))
}
#return: 
# array X with X[i,j,k] the number of subjects with level j of factor i in treatment k. X[i,j,k]=NA if j>numLevels(factor i).
# assignment vector with assignment[s] the treatment assignment of subject s
# error code: 1 means error, 0 means no errors detected
```



```{r data_gen}
#' 
#' @param n.subj number of subjects
#' @param k.arms number of arms
#' @param n.sites number of sites
#' @param bin.props vector of probabilities of successes for each binary covariate. 
#' The length of the vector determines the number of binary covariates
#' @param bin.iccs vector of intra-cluster correlation coefficients the same length as bin.props, or a single constant that will be used for all covariates
#' 
#' 
GenerateStudyData <- function(i = 1, n.subj = 600, k.arms = 4, n.sites = 10, bin.props = runif(5, min = .1, max = .9), bin.iccs = .1,
                              ...) {
  study_data <- tibble(ID = 1:n.subj,
                       Site = sample(1:n.sites, size = n.subj, replace = TRUE)) %>%
    MakeCorrelatedBinaryCovars(indf = ., bin.props = bin.props, bin.iccs = bin.iccs)
    
    covar_matrix <- study_data %>% 
      select(Site, starts_with("X_")) %>% 
      mutate_all(factor) %>%  mutate_all(as.numeric)  %>% #balanceRandomize function is expecting factor levels starting at 1 not 0 or -1
      as.matrix
    
    study_data$A1 <- balanceRandomize(Z = covar_matrix, 
                                   N = k.arms, 
                                   ...)$assignment
    
  return(study_data)
}

#' Create cluster-correlated binary covariates using the \code{fabricatr} package. 
#' @param indf the current data frame
#' @param bin.props vector of probs; probabilities (proportions) with binary
#' covariate = 1
#' @param bin.iccs vector of intra-cluster correlation coefficients the same length as bin.props, or a single constant that will be used for all covariates
#' 
#' @return the input data frame with the covariates appended
MakeCorrelatedBinaryCovars <- function(indf, bin.props, bin.iccs){
  stopifnot("Site" %in% colnames(indf))
  num_covars <- length(bin.props)
  
  if(num_covars == 0) return(indf)
  
  # Recycle bin.iccs so its length matches num_covars
  if(length(bin.iccs) < num_covars){
    if(length(bin.iccs) > 1) warning("Length of bin.iccs and bin.props do not match and bin.iccs is not a constant. Recycling bin.iccs, verify this mismatch is intended")
    bin.iccs <- rep(bin.iccs, length.out = num_covars)
  }
  
  # Create covariates
  bin_covar_mat <- matrix(nrow = nrow(indf), ncol = num_covars)
  
  for(i in 1:num_covars){
    bin_covar_mat[,i] <- fabricatr::draw_binary_icc(prob = bin.props[i],
                                                    clusters = indf$Site,
                                                    ICC = bin.iccs[i])
  }
  
  # Naming
  covar_names <- paste("X", 1:num_covars, sep = "_")
  colnames(bin_covar_mat) <- covar_names
  
  df_with_bin_covars <- bind_cols(indf, as_tibble(bin_covar_mat))
  
  return(df_with_bin_covars)
}

```


```{r imbalance_code}

#' Calculates study-wide maximum treatment imbalance, 
#' study-wide maximum treatment imbalance by factor level,
#' site-level treatment imbalance, and
#' site by covariate level imbalance
#'
#' @param indf data frame with study data. Site must be in a column named Site 
#' and treatment must be in a column named A1
#' @param

AnalyzeImbalances <- function(indf, vars.to.check){
  imbalance_across_study <- vector("numeric", length = length(vars.to.check))
  
  ImbalanceHelper <- function(indf, cur.var){
    allocation_table <- indf %>% group_by(!!sym(cur.var)) %>% group_map( .f = ~table(.$A1))
    imbalance_by_level <- map_dbl(allocation_table, ~diff(range(.)))
    
    return(imbalance_by_level)
  }
  
  
  study_level_imbalances <- map(vars.to.check, ~ImbalanceHelper(indf, .)) %>% unlist
  
  cluster_level_imbalances <- indf %>%  group_by(Site) %>% 
    group_map(., .f = function(x, ...) map(vars.to.check, ~ImbalanceHelper(indf = x, .) %>% unlist)) %>% 
    unlist
  
  cluster_treatment_imbalances <- indf %>% group_by(Site) %>% 
    group_map(., ~max(diff(range(table(.$A1))))) %>% 
    unlist
  
  imbalance_summary <- c("MaxTreatmentImbalance" = max(diff(range(table(indf$A1)))),
                         "MaxStudywideCovImbalance" = max(study_level_imbalances),
                         "MaxSiteTreatmentImbalance" = max(cluster_treatment_imbalances),
                         "MaxSiteCovImbalance" = max(cluster_level_imbalances))  
  return(imbalance_summary)
}
```

```{r test_sim, cache=TRUE}
sim_reps <- 5L
covariate_dimensions <- 1:6
sim_seed <- 8834
# Seed from https://nclottery.com/Pick4 Wednesday Daytime Draw 05-12-21

coin_bias <- 2/3

  
MapWrapper <- function(d.dim){
  setting_run <- future_map(seq_len(sim_reps), 
                              ~GenerateStudyData(i = ., 
                                                 n.subj = 600,
                                                 k.arms = 4, 
                                                 n.sites = 8, 
                                                 bin.props = seq(from = .1, to = .9, length.out = d.dim), 
                                                 bin.iccs = .05,
                                                 bias = coin_bias,
                                                 formula = 'a'),
                              .options = furrr_options(seed = sim_seed))
  return(setting_run)
}

ImbalanceWrapper <- function(df.list, d.dim){
  future_map_dfr(df.list, ~AnalyzeImbalances(indf = ., vars.to.check = paste0("X_", 1:d.dim)))
}


sim_data_list_method_a <- map(covariate_dimensions, MapWrapper)

imbalance_results_a <- map2(sim_data_list_method_a, covariate_dimensions, ImbalanceWrapper) %>% 
  bind_rows( .id = "Covariates") %>% 
  mutate(Covariates = covariate_dimensions[as.numeric(Covariates)])

imbalance_long_a <- imbalance_results_a %>% pivot_longer(cols = ends_with("Imbalance"), 
                                     names_pattern = "(.*)Imbalance",
                                     names_to = "Comparison",
                                     values_to = "MaxImbalance") %>% 
  mutate_at(., "Comparison", ~factor(., levels = c("MaxTreatment",
                                                  "MaxStudywideCov",
                                                  "MaxSiteTreatment",
                                                  "MaxSiteCov"),
                                    labels = c("Study-wide",
                                               "Factor across study",
                                               "Within-site",
                                               "Factor within site")))

imbalance_summary_a <- imbalance_long_a %>% group_by(Covariates, Comparison) %>% 
  group_modify(~ {
    .x %>%
      purrr::map_dfc(fivenum) %>%
      mutate(nms = c("Min", "Q1", "Median", "Q3", "Max"))
  }) %>% 
  pivot_wider(names_from = "nms", values_from = "MaxImbalance") %>% 
  arrange(Comparison, Covariates)

plan(sequential)
```

# Simulation Results

The results are based on `r sim_reps` replications per covariate setting for `r paste(covariate_dimensions, collapse = ", ")` covariates. The biased coin probability was `r round(coin_bias, 2)`. A longer write-up to come soon™ 

```{r results_tbl, echo = FALSE}
knitr::kable(imbalance_summary_a, align = "c", caption = "Five-number Summary of Treatment Imbalance by Number of Covariates in the Minimization", row.names = FALSE)
```

# Code

```{r get-labels, echo = FALSE}
labs = knitr::all_labels()
lib_lab = "libs"
min_lab = "minimization"
labs = setdiff(labs, c("setup", "get-labels", "results_tbl"))
```

```{r lib-code, ref.label=lib_lab, eval=FALSE, echo = TRUE}
```

## Minimization


```{r min-code, ref.label=min_lab, eval=FALSE, echo=TRUE}
```

## Data Generation

```{r min-code, ref.label="data_gen", eval=FALSE, echo=TRUE}
```

## Performance metrics

```{r min-code, ref.label="imbalance_code", eval=FALSE, echo=TRUE}
```


## Simulation code

```{r min-code, ref.label="test_sim", eval=FALSE, echo=TRUE}
```